name: Deploy Demo

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and deploy
        run: |
          npm ci --legacy-peer-deps
          npm run build-lib
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
